services:
  api: 
    build:
      context: red-social-web
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./red-social-web:/app
    ports: 
      - '8000:8000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@db:3312/${DB_DATABASE}
      
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    networks:
      - app-network

  # db-mysql:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   ports:
  #     - 3312:3306
  #   environment:
  #     - MYSQL_DATABASE=${DB_DATABASE}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_USER=${DB_USERNAME}
  #     - TZ= UTC
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   command:  --default-authentication-plugin=caching_sha2_password
    

networks:
  app-network:
    driver: bridge