# Generated by Django 5.1 on 2024-10-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(default='=805MHj0', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role'),
        ),
    ]
