# Generated by Django 5.1 on 2024-10-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_subscriptionplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='imageCover',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
