# Generated by Django 5.1 on 2024-10-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_subscriptionplan_imagecover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttokendiscount',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='paymenttokendiscount',
            name='subscription_plans',
            field=models.ManyToManyField(related_name='discount_tokens', to='payment.subscriptionplan'),
        ),
    ]
