# Generated by Django 5.1 on 2024-10-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_paymenttokendiscount_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttokendiscount',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
