# Generated by Django 5.1 on 2024-10-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_paymenttokensaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttokensaccess',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttokensaccess',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
