# Generated by Django 5.1 on 2024-08-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectiondate',
            old_name='name_period',
            new_name='description',
        ),
    ]
