# Generated by Django 5.1 on 2024-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0002_alter_institution_type_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemetrics',
            name='followers',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='basemetrics',
            name='publications',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='basemetrics',
            name='reactions',
            field=models.BigIntegerField(),
        ),
    ]
