# Generated by Django 5.1 on 2024-08-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0003_alter_basemetrics_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemetrics',
            old_name='engagment_rate',
            new_name='Average_views',
        ),
    ]
