# Generated by Django 5.1 on 2024-08-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0004_rename_engagment_rate_basemetrics_average_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStatsByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_followers', models.BigIntegerField(default=0)),
                ('total_publications', models.BigIntegerField(default=0)),
                ('total_reactions', models.BigIntegerField(default=0)),
                ('average_views', models.FloatField(default=0.0)),
                ('institution_count', models.IntegerField(default=0)),
                ('stats_date', models.DateField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_metrics.socialnetwork')),
                ('type_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_metrics.typeinstitution')),
            ],
            options={
                'unique_together': {('type_institution', 'social_network', 'stats_date')},
            },
        ),
    ]
