# Generated by Django 5.1 on 2024-08-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0005_institutionstatsbytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionstatsbytype',
            name='average_views',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='institutionstatsbytype',
            name='institution_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='institutionstatsbytype',
            name='total_followers',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='institutionstatsbytype',
            name='total_publications',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='institutionstatsbytype',
            name='total_reactions',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
