# Generated by Django 5.1 on 2024-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0006_alter_institutionstatsbytype_average_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionstatsbytype',
            name='institution_count',
        ),
        migrations.AddField(
            model_name='typeinstitution',
            name='institution_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='typeinstitution',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
