# Generated by Django 5.1 on 2024-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0009_rename_percent_correction_socialnetwork_percentage_correction_social_networks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinstitution',
            name='category',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
