# Generated by Django 5.1 on 2024-09-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0010_typeinstitution_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='percentage_correction_social_networks',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='percentage_correction_type_institutions',
        ),
    ]
