# Generated by Django 5.1 on 2024-09-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0011_remove_socialnetwork_percentage_correction_social_networks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='percentage_correction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='typeinstitution',
            name='percentage_correction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
