# Generated by Django 5.1 on 2024-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_metrics', '0012_socialnetwork_percentage_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinstitution',
            name='percentage_correction_in_network_social',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
