# Generated by Django 5.1 on 2024-08-28 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type_identification',
        ),
    ]
